### ISSUE TITLE
Spiegare una battuta è come sezionare una rana. non piace a nessuno, e nel procedimento la rana muore.

### ISSUE THREAD

**Issue by Gunnegan** [unhorsing/ways-of-saying#92]
Explaining a joke is like dissecting a frog. Noone likes it, and in the process the frog dies.

A little long, maybe, but really important to know.

**Comment by m4ng0** [comment]
@Gunnegan, thank you for your first contribution. I think we have a problem, because this one seems to be well known in the English-speaking world (see for example https://www.reddit.com/r/Jokes/comments/5gog41/explaining_a_joke_is_like_dissecting_a_frog/).
This could defeat the purpose of this project, that is to provide a literal and/or fancy translation for Italian or local idioms.

What do others think about this?

**Comment by Gunnegan** [comment]
I really understand.
this joke rules great part of my life. But I deeply understand the meanings of this project, so this joke should not be approved.
Sadly.

**Comment by m4ng0** [comment]
I didn't want to cause this sadness. Keep working hard, and the next one will be a success!
